### DISCUSSION TITLE
Add prefix to all outgoing request

### DISCUSSION THREAD

**Discussion by ElevnLi** [cvat-ai/cvat#3984] [Q&A]
Hey there,

We are trying to integrate cvat into out open source [Weed annotation platform](https://weed-ai.sydney.edu.au/).
We want to deploy cvat behind our nginx reverse proxy, and direct all the traffic of https://weed-ai.sydney.edu.au/annotation/ to traefik and then to cvat and cvat-ui. I'm using the traefik middleware to strip the prefix of the request like below:

```yaml
  cvat:
    container_name: cvat
    image: openvino/cvat_server
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      ADAPTIVE_AUTO_ANNOTATION: 'false'
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat.loadbalancer.server.port=8080
      - traefik.http.routers.cvat.rule=Host(`${CVAT_HOST:-localhost}`) &&
          PathPrefix(`/annotation/api/`, `/annotation/git/`, `/annotation/opencv/`, `/annotation/analytics/`, `/annotation/static/`, `/annotation/admin`, `/annotation/documentation/`, `/annotation/django-rq`)
      - traefik.http.routers.cvat.entrypoints=web
      - traefik.http.routers.cvat.middlewares=add-cvat
      - traefik.http.middlewares.add-cvat.stripprefix.prefixes=/annotation
      - traefik.http.middlewares.add-cvat.stripprefix.forceSlash=true
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat
```

Then when I request http://localhost/annotation/api/v1/tasks/2/data?type=preview, it's able to cut off the prefix.
My question is that is there a field you left for the frontend image or do you know a way to add prefix to every outgoing request, like when the frontend is communicating with the back, instead of requesting /api/..., it's requesting /annotation/api/..., then it's able to be redirected correctly.

Thanks for your help! We are really enjoying your work and happy to integrate it as a significant component of our platform.

Best,
Elevn
