### DISCUSSION TITLE
Need help running CVAT on a remote host and accessing locally

### DISCUSSION THREAD

**Discussion by rohangirishrao** [cvat-ai/cvat#9185] [Q&A]
Hi everyone, I'm new to the CVAT community, and I'm trying to run it on a VM on the server and access it remotely, so that multiple users can annotate videos. I cannot use the online version of CVAT due to the nature of the videos (medical videos).

I have got up to the point of changing `docker-compose.override.yaml` to allow the port to be accessed remotely, and I can see the UI remotely. But I cannot log in, even though I have set up a superuser.  How can I get the UI to work on the port but also log in ? I'm getting multiple errors such as 405: Not allowed and "check browser console for details". Any help is much appreciated! 
I have used the common AI tools to get some help and it hasn't really helped, I don't think. 
My docker-override file: 
```
services:
  cvat_server:
    ports:
      - "8080:8080"
    environment:
      - ALLOWED_HOSTS=*
    restart: always
    depends_on:
      - cvat_db
      - cvat_ui

  cvat_ui:
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - cvat_server
      - cvat_db
```
