### ISSUE TITLE
 A CrashLoopBackOff error occurs in the traefik pod after helm deploy. How do I resolve it?

### ISSUE THREAD

**Issue by JeongHanJun** [cvat-ai/cvat#7332]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. git clone

2. Refer to the guidelines and install helm/minikube/kube*

3. Create a custom values.yaml file
values.yaml : detail custom
cvat.values.yaml : traefik.service.externalIPs
4. minikube start
$ minikube start --addons registry,registry-aliases --memory 7700
5. helm deploy
$ helm upgrade -n cvat cvat -i --create-namespace ./helm-chart -f ./helm-chart/values.yaml -f ./helm-chart/cvat.values.yaml
6. check pods
$ kubectl get all -n cvat
![image](https://github.com/opencv/cvat/assets/54197360/f998a2ec-6553-4c95-843d-6c6529cb8cee)

### Expected Behavior

Expect all pods to be Running and STATE 1/1 normally.

Then, I can use CVAT normally by performing post-deploy details.

### Possible Solution

I tried various custom solutions to resolve this error.

1. A memory option was added to $ minikube start to use more memory to reduce the risk of capacity-related issues.
2. The yaml file used for deploy was modified as follows. We attempted to resolve capacity-related issues by increasing probe settings and resources.
```
cvat:
  backend:
.....
server:
      replicas: 1
      labels: {}
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
      annotations: {}
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
```
3. By adjusting the settings of the keydb pod, Pending STATE is not output from the keydb pod.
```
traefik:
  additionalArguments:
    - "--serverstransport.maxidletimeout=180s"
    - "--serverstransport.forwardingtimeouts.dialtimeout=180s"
    - "--serverstransport.forwardingtimeouts.responsetimeout=180s"
  deployment:
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 20
      failureThreshold: 20
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 20
      failureThreshold: 20
.......

resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
```
4. In the yaml to deploy, adjust the additionalArguments and Probe settings in the Traefik section to prevent timeout issues.
```
traefik:
  additionalArguments:
    - "--serverstransport.maxidletimeout=180s"
    - "--serverstransport.forwardingtimeouts.dialtimeout=180s"
    - "--serverstransport.forwardingtimeouts.responsetimeout=180s"
  deployment:
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 20
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 20
      
  enabled: false
  logs:
    general:
      format: json
    access:
      enabled: true
      format: json
      fields:
        general:
          defaultmode: drop
          names:
            ClientHost: keep
            DownstreamContentSize: keep
            DownstreamStatus: keep
            Duration: keep
            RequestHost: keep
            RequestMethod: keep
            RequestPath: keep
            RequestPort: keep
            RequestProtocol: keep
            RouterName: keep
            StartUTC: keep

```
Based on the above, various values ​​were adjusted.

$ kubectl describe pod -n cvat {traefik pod name}
If you run the above command to check,
Exit Code 1 or 2 is output.

I don't know what part of me is wrong or how to fix it.

Even if I use the $ kubectl logs command, I don't know what part to fix.

### Context

I want to deploy CVAT with Minikube.

Afterwards, I will build my own organization and form members. Of course, for this you need to perform post-deploy create superuser. However, you cannot proceed to this step due to a CrashLoopBackOff error in the Traefik pod.

Afterwards, we plan to import up to 1GB of pre-annotated coco dataset so that we can perform data annotation work on other IPs.

Afterwards, I would like to download the data I worked on.

I would greatly appreciate it if you could help me resolve this issue.

Also, if you have any experience solving a related issue, we would greatly appreciate it if you could share it with us.

If possible, please let us know in as much detail as possible, step by step!

### Environment

```Markdown
minikube version: v1.32.0
helm version: v3.13.2
kubectl version:
  Client Version: v1.28.2
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
git version: 2.25.1
```
