### ISSUE TITLE
Helm deployment 405 status code on login

### ISSUE THREAD

**Issue by waryak** [cvat-ai/cvat#7801]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Clone repo 
2. `git checkout remotes/origin/release-2.7.6`
3. `helm upgrade -n cvat cvat-test-depl -i . -f ./values.yaml -f ./values.override.yaml`
4. `kubectl port-forward -n cvat service/cvat-test-depl-frontend-service  8080:80`

### Expected Behavior

After user creation, I navigate to `localhost:8080` and  login via login form.

### Possible Solution

There are straightforward solutions for that in the internet: https://stackoverflow.com/questions/24415376/post-request-not-allowed-405-not-allowed-nginx-even-with-headers-included

But I wasn't able to perform that change in the container - nginx could reload that config

### Context

```
➜  ~ kubectl get pods --namespace cvat
NAME                                                              READY   STATUS      RESTARTS      AGE
cvat-test-depl-backend-initializer-r1-l8fnc                       0/1     Completed   0             5m5s
cvat-test-depl-backend-server-5949c6766b-lknlk                    1/1     Running     0             5m5s
cvat-test-depl-backend-utils-5698d6d648-78xmd                     1/1     Running     0             5m4s
cvat-test-depl-backend-worker-analyticsreports-7854b4ff69-6zzwp   1/1     Running     0             5m5s
cvat-test-depl-backend-worker-annotation-654cf6fc4c-bwhw7         1/1     Running     0             5m5s
cvat-test-depl-backend-worker-export-dd9986cdf-7jvdl              1/1     Running     0             5m4s
cvat-test-depl-backend-worker-export-dd9986cdf-kq2cz              1/1     Running     0             5m4s
cvat-test-depl-backend-worker-import-6784595667-rqz5f             1/1     Running     0             5m4s
cvat-test-depl-backend-worker-import-6784595667-vfpm4             1/1     Running     0             5m4s
cvat-test-depl-backend-worker-qualityreports-7547d6dd65-t96lv     1/1     Running     0             5m5s
cvat-test-depl-backend-worker-webhooks-5654488db-7nl5c            1/1     Running     0             5m5s
cvat-test-depl-frontend-5477899666-9fg79                          1/1     Running     0             5m4s
cvat-test-depl-keydb-0                                            1/1     Running     0             5m4s
cvat-test-depl-opa-6b4d9dd676-zdvtb                               1/1     Running     0             5m5s
```

<img width="1112" alt="405error" src="https://github.com/cvat-ai/cvat/assets/19685758/bfa03d3c-1c64-4975-adf3-fb1a1b6ba3bf">

### Environment

```Markdown
- Kubernetes version 1.28.6
- Cvat version - 2.7.6
- I also disables `analytics` in `values.yaml`
```

Also, here is my `values.override.yaml`

```YAML
analytics:
  enabled: false

postgresql:
  enabled: false # false for external db
  external:
    host: <>
    port: 5432

redis:
  enabled: false
  external:
    host: <>
  secret:
    password: <>
```

I tried to use external and internal setups for redis and postgres - the error persists

**Comment by waryak** [comment]
Also, here is my `override.yaml`

```
analytics:
  enabled: false


postgresql:
  enabled: false # false for external db
  external:
    host: <>
    port: 5432

redis:
  enabled: false
  external:
    host: <>
  secret:
    password: <>
```
