### ISSUE TITLE
CVAT on different ec2 instances to share volume in a efs(elastic file system)

### ISSUE THREAD

**Issue by gwengusc** [cvat-ai/cvat#7856]
I deployed CVAT on different ec2 instances, a efs (You can think of it as a external hard disk) is mounted to those ec2 instances. That is to say a efs is shared by all the ec2 instances. I deployed CVAT on different instances while docker volumes are sharing the same path pointing to the efs. However, the first instance deployed with CVAT runs well. The second one always failed. 

Any suggestion for this? How to deploy CVAT for instances scaling and centralize instances? Simply speaking, how to separate processor and storage, want to separate db, data,cache in order to centrally manage them.

```
volumes:
  cvat_db:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=fs-09aadb348745cd910.efs.us-west-2.amazonaws.com,rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/volumes/cvat_db"
  cvat_data:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=fs-09aadb348745cd910.efs.us-west-2.amazonaws.com,rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/volumes/cvat_data"
  cvat_keys:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=fs-09aadb348745cd910.efs.us-west-2.amazonaws.com,rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/volumes/cvat_keys"
  cvat_logs:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=fs-09aadb348745cd910.efs.us-west-2.amazonaws.com,rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/volumes/cvat_logs"
  cvat_events_db:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=fs-09aadb348745cd910.efs.us-west-2.amazonaws.com,rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/volumes/cvat_events_db"
  cvat_cache_db:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=fs-09aadb348745cd910.efs.us-west-2.amazonaws.com,rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/volumes/cvat_cache_db"
  cvat_inmem_db:
```
