### ISSUE TITLE
Store image & annotation data on a mounted drive

### ISSUE THREAD

**Issue by PAmerikanos** [cvat-ai/cvat#7979]
We are running CVAT on a cloud instance (AWS & Digital Ocean), and are looking for a way to store all uploaded data, not on the instance's primary drive, but on an externally attached storage volume (e.g. /mnt/drive_name/).

We tried adding a shared drive as mentioned here (https://docs.cvat.ai/docs/administration/basics/installation/#share-path), but it could not store uploaded data.

We tried modifying the `docker-compose.yml` file's `cvat_db` and `cvat_data` paths, but to no avail.

Are we missing something? Is there a guide perhaps?
Thanks

**Comment by bsekachev** [comment]
To achieve that you need to setup `cvat_db` and `cvat_data` volumes to save them on external storage. So, your initial steps were right, I do not know what was unsuccessful. 
Please, try to find a documentation on how to do that in docker-compose community.

**Comment by PAmerikanos** [comment]
Related issues:
- https://github.com/cvat-ai/cvat/issues/7979
- https://github.com/cvat-ai/cvat/issues/6119

**Solution:**
Under `/cvat` create `docker-compose.override.yml` with the following lines and rerun `docker up/down`:

```
volumes:
  cvat_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/PATH_TO_TARGET_DIR/cvat_data
```
