### ISSUE TITLE
Could not mount on connected file share

### ISSUE THREAD

**Issue by silaopi** [cvat-ai/cvat#8889]
I follow the installation guide to mount a local path, but it doesn't work.
![image](https://github.com/user-attachments/assets/afd747a1-3586-4eda-859d-38d91ae16c2d)

Here is my `docker-compose.override.yml` file:
[docker-compose.override.txt](https://github.com/user-attachments/files/18273201/docker-compose.override.txt)

By the way, I am using cvat 2.9.0, Ubuntu 20.04

**Comment by zhiltsov-max** [comment]
Hi, how you're starting CVAT?

**Comment by silaopi** [comment]
> Hi, how you're starting CVAT?
I start CVAT by using this command:
`docker compose -f docker-compose.override.yml up -d `

**Comment by zhiltsov-max** [comment]
I couldn't find any mentions in docker compose documentation for the bind volume syntax used in the file you shared. The following override worked for me:

<details>

```
services:
  cvat_server:
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - /mnt/cvat_share:/home/django/share:ro

  cvat_worker_import:
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - /mnt/cvat_share:/home/django/share:ro

  cvat_worker_export:
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - /mnt/cvat_share:/home/django/share:ro

  cvat_worker_annotation:
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - /mnt/cvat_share:/home/django/share:ro

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_events_db:
  cvat_cache_db:
```

</details>
