### ISSUE TITLE
How to deploy custom YOLO11 detection model on Nuclio??

### ISSUE THREAD

**Issue by patricklau12** [cvat-ai/cvat#9067]
Actions before raising this issue
- I searched the existing issues and did not find anything similar.
- I read/searched [the docs](https://docs.cvat.ai/docs/)

I spent many time to create the function-gpu.yaml and main.py and still not working....

nuctl get function pytorch-stf-yolov11 --platform local
 NAMESPACE | NAME                | PROJECT | STATE     | REPLICAS | NODE PORT 
 nuclio    | pytorch-stf-yolov11 | cvat    | unhealthy | 1/1      | 32788

**Comment by patricklau12** [comment]
> Have you looked at this manual? https://docs.cvat.ai/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models
> 
> It's also impossible to guess what's wrong with your function without any logs.

This is my function-gpu.yaml


```

metadata:
  name: pytorch-stf-yolov11
  namespace: cvat
  annotations:
    name: YOLO v11
    type: detector
    spec: |
      [
        { "id": 0, "name": "person", "type": "rectangle" },
        { "id": 1, "name": "bicycle", "type": "rectangle" },
        { "id": 2, "name": "motor vehicle", "type": "rectangle" },
        { "id": 3, "name": "e-scooter", "type": "rectangle" },
      ]

spec:
  description: YOLO v11 via pytorch
  runtime: 'python:3.8'
  handler: main:handler
  eventTimeout: 30s
  build:
    image: cvat.pytorch.stf.yolov11:latest-gpu     #it just the docker image name
    baseImage: nvidia/cuda:12.6.3-cudnn-runtime-ubuntu22.04

    directives:
      preCopy:
        - kind: USER
          value: root
        - kind: RUN
          value: apt update && apt install -y git libgl1 --no-install-recommends && rm -rf /var/lib/apt/lists/*
        - kind: WORKDIR
          value: /opt/nuclio
        - kind: RUN
          value: pip install ultralytics opencv-python-headless torch torchvision torchaudio
        - kind: WORKDIR
          value: /opt/nuclio
        # - kind: RUN
        #   value: cp /home/imse4090_1/Project_SmartTrafficSystem/Models/yolo11L_custom.pt /opt/nuclio/yolo11L_custom.pt
        - kind: RUN
          value: ln -s /usr/bin/python3 /usr/bin/python

  triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432 # 32MB

  resources:
    limits:
      nvidia.com/gpu: 1

  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume

```


And main.py
```
import os
import json
import numpy as np
import cv2
import torch
from ultralytics import YOLO
from PIL import Image

# Load labels from function.yaml
import yaml

def load_labels():
    with open("/opt/nuclio/function.yaml", 'rb') as function_file:
        functionconfig = yaml.safe_load(function_file)
    labels_spec = functionconfig['metadata']['annotations']['spec']
    return {item['id']: item['name'] for item in json.loads(labels_spec)}

# Load the YOLO 11 model
MODEL_PATH = "/opt/nuclio/yolo11L_custom.pt"
if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(f"Model file not found: {MODEL_PATH}")

model = YOLO(MODEL_PATH)
labels = load_labels()

def init_context(context):
    context.logger.info("Initializing YOLO 11 PyTorch model...")
    context.user_data.model = model
    context.user_data.labels = labels
    context.logger.info("Model loaded successfully!")

def handler(context, event):
    context.logger.info("Running YOLO 11 PyTorch model...")
    
    # Decode image from base64
    data = event.body
    image_bytes = base64.b64decode(data["image"])
    threshold = float(data.get("threshold", 0.5))

    # Convert image to OpenCV format
    image_array = np.frombuffer(image_bytes, np.uint8)
    image = cv2.imdecode(image_array, cv2.IMREAD_COLOR)

    # Run YOLO 11 inference
    results = context.user_data.model(image)[0]  # Get first result

    # Parse detections
    detections = []
    for box in results.boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        conf = float(box.conf[0])
        cls_id = int(box.cls[0])

        # Only include detections above the threshold
        if conf >= threshold:
            detections.append({
                "bbox": [x1, y1, x2, y2],
                "confidence": conf,
                "class_id": cls_id,
                "class_name": labels.get(cls_id, f"class_{cls_id}")  # Use CVAT labels
            })

    return context.Response(
        body=json.dumps(detections),
        headers={"Content-Type": "application/json"},
        status_code=200
    )

```
