### ISSUE TITLE
How to use external S3 Bucket as CVAT Backend storage?

### ISSUE THREAD

**Issue by A-Kod** [cvat-ai/cvat#9112]
Hello !

Now in my CVAT Backend Configuration is used PV & PVC in K8s. I have deployed it via helm Chart. 

The problem is that my cloud provider supports only RWO access mode for storage. So in this architecture it causes scalability problems - backend pods should be strictly launched only on a K8s node with this PV attached. 

So the solution seems to me - is to **use S3 Bucket** instead PV storages.  
But I searched through docs - and I couldn't understand, how to use S3 Bucket for Backend Storage. 

Can you please help me to find a solution for this. 

Now I have such configuration. What do I have to change to **use S3 Bucket as a CVAT backend storage** ?

```
cvat:
  backend:
    defaultStorage:
        enabled: true
        storageClassName: <my-cloud-provider-class-name>
        accessModes:
         - ReadWriteOnce
        size: "2600Gi"
```

My cvat backend version: v2.11.0
