### ISSUE TITLE
Problems with data import using SharePath

### ISSUE THREAD

**Issue by DP1701** [cvat-ai/cvat#9310]
Hello,

I have spent hours trying to achieve the following on macOS. Install CVAT and configure it so that data can be imported with a SharePath. However, the data should then be stored on an external hard disk. This is my docker-compose.override.yml:

```yaml
services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_annotation:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_chunks:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /Volumes/Data4TB/CVAT/SHARE
      o: bind
```

I have changed this in docker-compose.yml:

```yaml
volumes:
  cvat_db:
  cvat_data:
    driver_opts:
      type: none
      device: /Volumes/Data4TB/CVAT/DATA
      o: bind
  cvat_keys:
  cvat_logs:
  cvat_inmem_db:
  cvat_events_db:
  cvat_cache_db:
```

Now comes the strange behavior. If I do not run the following command in the terminal beforehand, CVAT does not show the SharePath folder when a new task is created.

```
find /Volumes/Data4TB/CVAT/SHARE \( -name '._*' -o -name '.DS_Store' \) -delete
```
It removes the metadata in the folder. But even if I then select the folder and choose the option “Copy data into CVAT”, I get the following error message in the console: 

<img width="542" alt="Image" src="https://github.com/user-attachments/assets/ba71cefd-b77e-408a-ba25-a3224a4bedea" />

When copying the images to the Data folder, there seem to be problems with the metadata being recreated. Does anyone have a solution to this problem?

macOS 15.3.1
CVAT v2.32.1
