### ISSUE TITLE
SQLDatasourceMaxOpenConnsDefault not set in config

### ISSUE THREAD

**Issue by raknamber1** [cvat-ai/cvat#9477]
I deployed it using helm chart tags v2.32.0
Ingress nginx.

When opening /analytics, I get

![Image](https://github.com/user-attachments/assets/ae9eb77a-5069-40b6-aa9c-07bd29e732df)

![Image](https://github.com/user-attachments/assets/63e3d3ee-b363-4db7-85e7-422ae209d742)

Logs grafana:

```
logger=plugin.grafana-clickhouse-datasource t=2025-05-27T17:48:43.927718765Z level=debug msg="Plugin Request Started" dsName=ClickHouse dsUid=PDEE91DDB90597936 endpoint=queryData pluginId=grafana-clickhouse-datasource uname=
logger=plugin.grafana-clickhouse-datasource t=2025-05-27T17:48:43.927811558Z level=error msg="Partial data response error" dsUid=PDEE91DDB90597936 error="SQLDatasourceMaxOpenConnsDefault not set in config" refID=0.35692663672806724 uname= dsName=ClickHouse endpoint=queryData pluginId=grafana-clickhouse-datasource status=500 statusSource=downstream
logger=plugin.grafana-clickhouse-datasource t=2025-05-27T17:48:43.927832861Z level=error msg="Plugin Request Completed" dsName=ClickHouse duration=164.759µs endpoint=queryData uname= dsUid=PDEE91DDB90597936 pluginId=grafana-clickhouse-datasource status=error statusSource=downstream
logger=plugin.grafana-clickhouse-datasource t=2025-05-27T17:48:43.927937416Z level=debug msg="Plugin Request Started" dsName=ClickHouse dsUid=PDEE91DDB90597936 endpoint=queryData pluginId=grafana-clickhouse-datasource uname=
logger=plugin.grafana-clickhouse-datasource t=2025-05-27T17:48:43.927976366Z level=error msg="Partial data response error" error="SQLDatasourceMaxOpenConnsDefault not set in config" refID=0.037520164014123614 statusSource=downstream dsName=ClickHouse dsUid=PDEE91DDB90597936 endpoint=queryData pluginId=grafana-clickhouse-datasource status=500 uname=
logger=context userId=-1 orgId=1 uname= t=2025-05-27T17:48:43.927987521Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=IP_ADDR time_ms=9 duration=9.016132ms size=124 referer="https://my_domain/analytics/?orgId=1" handler=/api/ds/query
logger=plugin.grafana-clickhouse-datasource t=2025-05-27T17:48:43.928000238Z level=error msg="Plugin Request Completed" statusSource=downstream dsUid=PDEE91DDB90597936 duration=158.035µs status=error dsName=ClickHouse endpoint=queryData pluginId=grafana-clickhouse-datasource uname=
logger=context userId=-1 orgId=1 uname= t=2025-05-27T17:48:43.928069144Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=IP_ADDR time_ms=8 duration=8.066555ms size=125 referer="https://my_domain/analytics/?orgId=1" handler=/api/ds/query
```

helm setting grafana default:
```
grafana:
  envFromSecret: cvat-analytics-secret
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: 'ClickHouse'
        type: 'grafana-clickhouse-datasource'
        isDefault: true
        jsonData:
          defaultDatabase: ${CLICKHOUSE_DB}
          port: ${CLICKHOUSE_PORT}
          server: ${CLICKHOUSE_HOST}
          username: ${CLICKHOUSE_USER}
          tlsSkipVerify: true
          protocol: http
        secureJsonData:
          password: ${CLICKHOUSE_PASSWORD}
        editable: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
  dashboardsConfigMaps:
    default: "cvat-grafana-dashboards"
  plugins:
    - grafana-clickhouse-datasource
  grafana.ini:
    server:
      root_url: https://my_domain/analytics/
      serve_from_sub_path: true
    dashboards:
      default_home_dashboard_path: /var/lib/grafana/dashboards/default/all_events.json
    users:
      viewers_can_edit: true
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
      org_role: Admin
    auth.basic:
      enabled: false
```

Any idea or help in solving the problem please
